### ISSUE TITLE
TODO List (02/04/2017)

### ISSUE THREAD

**Issue by PritamSangani** [PritamSangani/Tech-Wars#1]
## TODO

- [x] Add array of aliens
- [x] Create arrayList of Bullets
-  [x] Collision mechanism for aliens
- [x] Scoring and Lives for Defender
- [ ] Levels(increased alienSpeed)
- [ ] PowerUps for Defender
- [ ] GUI Screen so user can enter name
- [ ] High Scores
